### ISSUE TITLE
Disable tor

### ISSUE THREAD

**Issue by EgorChadov** [NOXCIS/Wiregate#69]
Hello!

Is it possible to turn off tor entirely? 

My current docker-compose is:

```
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.2.0.0/24


services:
  adguard:
    depends_on: [wiregate]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./configs/adguard/Data:/opt/adguardhome/work"
      - "./configs/adguard:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100   

  wiregate:
      #image: noxcis/wiregate:vidar
      image: noxcis/wiregate:jiaotu-beta-v0.4
      container_name: wiregate
      hostname: wiregate
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun  
      restart: unless-stopped
      volumes:
        - "./conf:/etc/wireguard"
        - "./pf_conf:/WireGate/iptable-rules/"
        - "./db:/WireGate/db"
        - "./configs/dnscrypt:/WireGate/dnscrypt"
        #- "./configs/tor:/etc/tor/"
        - "./configs/logs:/WireGate/log/"
        - "./configs/master-key:/WireGate/master-key"

      environment:
        #- WGDCONF_PATH=/etc/wireguard
        - AMNEZIA_WG=true

      #Tor Settings
      ##########################################################
        - WGD_TOR_PROXY=false          #Enable Tor
        - WGD_TOR_EXIT_NODES={}     #Ex. {gb},{fr}
        - WGD_TOR_DNS_EXIT_NODES={}
        - WGD_TOR_BRIDGES=false        #Enable Tor Bridges
        - WGD_TOR_PLUGIN=snowflake    #OPTIONS webtunnel, obfs4, snowflake
      #WGDashboard Global Settings
      ##########################################################
        - WGD_WELCOME_SESSION=false	  ##Promts user accont creation after fist sign in. 
        - WGD_AUTH_REQ=true
        - WGD_USER=admin
        - WGD_PASS=admin
        - WGD_REMOTE_ENDPOINT=#your domain or ip
        - WGD_REMOTE_ENDPOINT_PORT=80
        - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0, ::/0
        - WGD_KEEP_ALIVE=21
        - WGD_MTU=1384
        - WGD_PORT_RANGE_STARTPORT=4430
        - WGD_DNS=10.2.0.100
        - WGD_IPTABLES_DNS=10.2.0.100
      ports:
        - "4430-4433:4430-4433/udp" #UDP Interface Listen Ports For Zones
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1
      networks:
        private_network:
          ipv4_address: 10.2.0.3
```
          
          
As you can see WGD_TOR_PROXY and WGD_TOR_BRIDGES turned off. But tor is still running in system and container logs shows that  tor getting new bridges. Also button 'Bridges enabled' in web interface always green no matter what I'm choosing. 

![2025-01-13_02-04-32](https://github.com/user-attachments/assets/ea79ab72-392a-4b96-b286-6d8231f9376c)

![2025-01-13_02-05-06](https://github.com/user-attachments/assets/4771ee26-6a40-4b78-8620-fef550f3d0ba)

![2025-01-13_02-05-24](https://github.com/user-attachments/assets/8fb74756-04a2-433d-b0e4-1dc19d5b0324)
