### ISSUE TITLE
I can't connect.

### ISSUE THREAD

**Issue by Kuzz007** [NOXCIS/Wiregate#70]
Hello everyone!
Why can't I connect to the panel by IP address and port by default, if I understand correctly 8000
Or can I only connect as a localhost?

And in the manual as a whole nothing is written what and how

**Comment by NOXCIS** [comment]
Did you deploy via quick installer or Docker-Compose?

**Comment by Kuzz007** [comment]
Yes, Docker Compose installation.
With the usual installation, nothing is clear at all because there is no normal description, but this did not work either.

**Comment by Kuzz007** [comment]
> Вы выполнили развертывание с помощью быстрого установщика или Docker-Compose?

It also hangs the server )))

**Comment by NOXCIS** [comment]
@Kuzz007 
I set up a demo. couldnt replicate the issue
http://104.236.227.170:8000/#/signin
**username**: admin **password**: admin
git clone and the repo, cd into it and use the main.docker.compose.yml


````yaml
#Configure To YOUR Enviornment and RUN
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.2.0.0/24


services:
  dnscrypt:
    depends_on: [wiregate]
    image: "noxcis/dnscrypt:latest"
    restart: unless-stopped
    container_name: dnscrypt
    volumes:
      - ./configs/dnscrypt:/config
    networks:
      private_network:
        ipv4_address: 10.2.0.42

  unbound:
    depends_on: [dnscrypt]
    image: "noxcis/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "dnssec.works"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s 
    networks:
      private_network:
        ipv4_address: 10.2.0.200
  

  
  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./configs/adguard/Data:/opt/adguardhome/work"
      - "./configs/adguard:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100   

  wiregate:
      image: noxcis/wiregate:jiaotu-beta-dev-v0.2.3
      container_name: wiregate
      hostname: wiregate
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun  
      restart: unless-stopped
      volumes:
        - pf_conf:/WireGate/iptable-rules/
        - conf:/etc/wireguard 
        - db:/WireGate/db
        - ./configs/dnscrypt:/WireGate/dnscrypt
        - ./configs/tor:/etc/tor/
        - ./configs/logs:/WireGate/log/
        - ./configs/master-key:/WireGate/master-key

      environment:
      #Config Path Optional
        #- WGDCONF_PATH=/etc/wireguard
      #Use Ofuscated Wireguard (AmneziaWG)
        - AMNEZIA_WG=true
      #Set Timezone
        - TZ=America/New_York

      #Tor Settings
      ##########################################################
        - WGD_TOR_PROXY=false          #Enable Tor
        - WGD_TOR_EXIT_NODES={ch}     #Ex. {gb},{fr}
        - WGD_TOR_DNS_EXIT_NODES={us}
        - WGD_TOR_BRIDGES=true        #Enable Tor Bridges
        - WGD_TOR_PLUGIN=webtunnel    #OPTIONS webtunnel, obfs4, snowflake
      #WGDashboard Global Settings
      ##########################################################
        - WGD_WELCOME_SESSION=true
        - WGD_AUTH_REQ=true
        - WGD_USER=admin
        - WGD_PASS=admin
        - WGD_REMOTE_ENDPOINT=0.0.0.0
        - WGD_REMOTE_ENDPOINT_PORT=80
        - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0, ::/0
        - WGD_KEEP_ALIVE=21
        - WGD_MTU=1420
        - WGD_PORT_RANGE_STARTPORT=4430
      #DNS Setiings (Set To use Containers Above) You can use your own DNS
      ##########################################################
        - WGD_DNS=10.2.0.100
        - WGD_IPTABLES_DNS=10.2.0.100
      ports:
        - "4430-4433:4430-4433/udp" #UDP Interface Listen Ports For Zones
        - 8000:80/tcp #Comment Out for full network lockdown, I.E only Accessible via VPN conttenction at http://wire.gate using config in generated master-key folder
      sysctls:        #Otherwise access the dashboard @ your-sever-ip/domain:6060
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1
      networks:
        private_network:
          ipv4_address: 10.2.0.3
    


volumes:
    db:
    conf:
    pf_conf:
````
